'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {useParams} from 'next/navigation';import {supabase} from '../../../lib/supabase';import {ArrowLeft,UserRound,MapPin,CreditCard,Bell,LockKeyhole,Save,Plus,Trash2,Pencil,Check} from 'lucide-react';
const emptyAddress={label:'Home',address_line:'',suburb:'Eersterust',instructions:'',is_default:false};
const emptyPayment={method_type:'cash_on_delivery',display_label:'Cash on delivery',last4:'',is_default:true};
export default function AccountSection(){const{section}=useParams();const[user,setUser]=useState(null),[data,setData]=useState(null),[rows,setRows]=useState([]),[form,setForm]=useState(emptyAddress),[editing,setEditing]=useState(null),[show,setShow]=useState(false),[msg,setMsg]=useState(''),[busy,setBusy]=useState(true);
 const config={personal:{title:'Personal Information',icon:UserRound,description:'Keep your contact details up to date for orders and delivery.'},addresses:{title:'Saved Addresses',icon:MapPin,description:'Save delivery addresses so checkout is faster and more accurate.'},'payment-methods':{title:'Payment Methods',icon:CreditCard,description:'Manage how you plan to pay for your orders.'},notifications:{title:'Notifications',icon:Bell,description:'Choose the updates you want to receive.'},'change-password':{title:'Change Password',icon:LockKeyhole,description:'Choose a strong password for your account.'}}[section];
 useEffect(()=>{(async()=>{if(!config){setMsg('This account setting could not be found.');setBusy(false);return}if(!supabase){setMsg('Supabase is not configured.');setBusy(false);return}const{data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/signin';return}setUser(user);if(section==='personal'){setData({email:user.email||'',name:user.user_metadata?.full_name||'',phone:user.user_metadata?.cellphone||user.phone||''});const{data:p}=await supabase.from('profiles').select('full_name,phone').eq('id',user.id).maybeSingle();if(p)setData(d=>({...d,name:p.full_name||d.name,phone:p.phone||d.phone}))}else if(section==='addresses'){const{data,error}=await supabase.from('customer_addresses').select('*').eq('customer_id',user.id).order('is_default',{ascending:false}).order('created_at',{ascending:false});setRows(data||[]);if(error)setMsg(error.message)}else if(section==='payment-methods'){const{data,error}=await supabase.from('payment_methods').select('*').eq('customer_id',user.id).order('is_default',{ascending:false}).order('created_at',{ascending:false});setRows(data||[]);if(error)setMsg(error.message)}else if(section==='notifications'){const{data:p}=await supabase.from('notification_preferences').select('*').eq('customer_id',user.id).maybeSingle();setData(p||{order_updates:true,promotions:false,account_alerts:true})}setBusy(false)})()},[section]);
 async function savePersonal(e){e.preventDefault();setBusy(true);setMsg('');const{error}=await supabase.auth.updateUser({email:data.email.trim(),phone:data.phone.trim()||undefined,data:{full_name:data.name.trim()}});if(error){setMsg(error.message);setBusy(false);return}const{error:e2}=await supabase.from('profiles').upsert({id:user.id,full_name:data.name.trim()||null,phone:data.phone.trim()||null,updated_at:new Date().toISOString()});setMsg(e2?e2.message:'Your personal information has been saved.');setBusy(false)}
 async function savePassword(e){e.preventDefault();setBusy(true);setMsg('');const p=e.currentTarget.password.value,c=e.currentTarget.confirm.value;if(p.length<6){setMsg('Your password must be at least 6 characters.');setBusy(false);return}if(p!==c){setMsg('Passwords do not match.');setBusy(false);return}const{error}=await supabase.auth.updateUser({password:p});setMsg(error?.message||'Your password has been changed.');if(!error)e.currentTarget.reset();setBusy(false)}
 async function loadAddresses(){const{data,error}=await supabase.from('customer_addresses').select('*').eq('customer_id',user.id).order('is_default',{ascending:false}).order('created_at',{ascending:false});setRows(data||[]);if(error)setMsg(error.message)}
 async function saveAddress(e){e.preventDefault();setBusy(true);if(form.is_default)await supabase.from('customer_addresses').update({is_default:false}).eq('customer_id',user.id);const payload={...form,customer_id:user.id,updated_at:new Date().toISOString()};const{error}=editing?await supabase.from('customer_addresses').update(payload).eq('id',editing).eq('customer_id',user.id):await supabase.from('customer_addresses').insert(payload);if(error)setMsg(error.message);else{setShow(false);await loadAddresses()}setBusy(false)}
 async function removeAddress(id){setBusy(true);const{error}=await supabase.from('customer_addresses').delete().eq('id',id).eq('customer_id',user.id);if(error)setMsg(error.message);else await loadAddresses();setBusy(false)}
 async function defaultAddress(id){setBusy(true);await supabase.from('customer_addresses').update({is_default:false}).eq('customer_id',user.id);await supabase.from('customer_addresses').update({is_default:true}).eq('id',id).eq('customer_id',user.id);await loadAddresses();setBusy(false)}
 async function loadPayments(){const{data,error}=await supabase.from('payment_methods').select('*').eq('customer_id',user.id).order('is_default',{ascending:false}).order('created_at',{ascending:false});setRows(data||[]);if(error)setMsg(error.message)}
 async function savePayment(e){e.preventDefault();setBusy(true);if(form.method_type==='card'&&!/^\d{4}$/.test(form.last4)){setMsg('Enter only the last 4 card digits. Never enter a full card number.');setBusy(false);return}if(form.is_default)await supabase.from('payment_methods').update({is_default:false}).eq('customer_id',user.id);const{error}=await supabase.from('payment_methods').insert({...form,customer_id:user.id});if(error)setMsg(error.message);else{setShow(false);await loadPayments()}setBusy(false)}
 async function removePayment(id){setBusy(true);const{error}=await supabase.from('payment_methods').delete().eq('id',id).eq('customer_id',user.id);if(error)setMsg(error.message);else await loadPayments();setBusy(false)}
 async function defaultPayment(id){setBusy(true);await supabase.from('payment_methods').update({is_default:false}).eq('customer_id',user.id);await supabase.from('payment_methods').update({is_default:true}).eq('id',id).eq('customer_id',user.id);await loadPayments();setBusy(false)}
 async function saveNotifications(e){e.preventDefault();setBusy(true);const{error}=await supabase.from('notification_preferences').upsert({customer_id:user.id,...data,updated_at:new Date().toISOString()});setMsg(error?'Could not save: '+error.message:'Notification preferences saved.');setBusy(false)}
 if(!config)return <main className="settings-page"><div className="settings-shell"><Link href="/account" className="settings-back"><ArrowLeft size={17}/> Account</Link><div className="settings-empty"><h2>Setting not found</h2><p>{msg}</p></div></div></main>;
 const Icon=config.icon;
 return <main className="settings-page"><div className="settings-shell"><Link href="/account" className="settings-back"><ArrowLeft size={17}/> Account</Link><div className="settings-hero"><span className="settings-icon"><Icon size={22}/></span><div><div className="eyebrow">Account settings</div><h1>{config.title}</h1><p>{config.description}</p></div>{section==='addresses'&&<button className="btn btn-primary" onClick={()=>{setEditing(null);setForm(emptyAddress);setShow(true);setMsg('')}}><Plus size={17}/> Add address</button>}{section==='payment-methods'&&<button className="btn btn-primary" onClick={()=>{setForm(emptyPayment);setShow(true);setMsg('')}}><Plus size={17}/> Add method</button>}</div>{msg&&<div className="notice settings-notice">{msg}</div>}
 {section==='personal'&&data&&<form className="settings-card settings-form" onSubmit={savePersonal}><label>Full name<input value={data.name} onChange={e=>setData({...data,name:e.target.value})} required/></label><label>Email address<input type="email" value={data.email} onChange={e=>setData({...data,email:e.target.value})} required/><small>Changing your email may require confirmation.</small></label><label>Cellphone number<input type="tel" value={data.phone} onChange={e=>setData({...data,phone:e.target.value})}/></label><button className="btn btn-primary" disabled={busy}><Save size={17}/>{busy?'Saving…':'Save changes'}</button></form>}
 {section==='change-password'&&<form className="settings-card settings-form" onSubmit={savePassword}><label>New password<input name="password" type="password" minLength={6} required/></label><label>Confirm new password<input name="confirm" type="password" minLength={6} required/></label><button className="btn btn-primary" disabled={busy}><Save size={17}/>{busy?'Updating…':'Change password'}</button></form>}
 {section==='notifications'&&data&&<form className="settings-card preference-card" onSubmit={saveNotifications}>{[['order_updates','Order updates','Receive status and delivery updates for your orders.'],['promotions','Offers and promotions','Receive optional promotions and new-store announcements.'],['account_alerts','Account alerts','Receive important security and account notifications.']].map(([key,title,description])=><label className="preference-row" key={key}><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" checked={data[key]} onChange={e=>setData({...data,[key]:e.target.checked})}/></label>)}<button className="btn btn-primary" disabled={busy}><Save size={17}/>{busy?'Saving…':'Save preferences'}</button></form>}
 {(section==='addresses'||section==='payment-methods')&&(!busy||rows.length>0)&&<div className="settings-stack">{rows.length?rows.map(r=><article className="settings-card address-card" key={r.id}><div className="settings-card-icon">{section==='addresses'?<MapPin size={18}/>:<CreditCard size={18}/>}</div><div className="settings-card-main"><div className="settings-card-title"><strong>{section==='addresses'?r.label:r.display_label}</strong>{r.is_default&&<span className="settings-badge"><Check size={12}/> Default</span>}</div><p>{section==='addresses'?[r.address_line,r.suburb].filter(Boolean).join(', '):r.method_type==='cash_on_delivery'?'Pay cash when your order arrives.':r.method_type==='eft'?'Bank transfer / EFT':'Card ending '+r.last4}</p>{section==='addresses'&&r.instructions&&<small>{r.instructions}</small>}</div><div className="settings-card-actions">{section==='addresses'&&<button onClick={()=>{setEditing(r.id);setForm({label:r.label,address_line:r.address_line,suburb:r.suburb,instructions:r.instructions||'',is_default:r.is_default});setShow(true)}}><Pencil size={17}/></button>}<button onClick={()=>section==='addresses'?removeAddress(r.id):removePayment(r.id)}><Trash2 size={17}/></button>{!r.is_default&&<button onClick={()=>section==='addresses'?defaultAddress(r.id):defaultPayment(r.id)}><Check size={17}/></button>}</div></article>):<div className="settings-empty"><Icon size={28}/><h2>No {section==='addresses'?'saved addresses':'payment methods'} yet</h2><p>{section==='addresses'?'Add your Eersterust delivery address for faster checkout.':'Start with cash on delivery, or add a masked card/EFT method.'}</p><button className="btn btn-primary" onClick={()=>{setForm(section==='addresses'?emptyAddress:emptyPayment);setShow(true)}}>Add {section==='addresses'?'address':'payment method'}</button></div>}</div>}
 {show&&<div className="settings-modal-backdrop"><form className="settings-modal" onSubmit={section==='addresses'?saveAddress:savePayment}><button type="button" className="settings-close" onClick={()=>setShow(false)}>×</button><div className="eyebrow">{editing?'Edit address':'New '+(section==='addresses'?'address':'payment method')}</div><h2>{editing?'Update your address':'Add a '+(section==='addresses'?'delivery address':'payment option')}</h2><div className="settings-form">{section==='addresses'?<><label>Label<input value={form.label} onChange={e=>setForm({...form,label:e.target.value})} required/></label><label>Street address<input value={form.address_line} onChange={e=>setForm({...form,address_line:e.target.value})} required/></label><label>Suburb<input value={form.suburb} onChange={e=>setForm({...form,suburb:e.target.value})} required/></label><label>Delivery instructions<textarea value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})}/></label></>:<><label>Method<select value={form.method_type} onChange={e=>setForm({...form,method_type:e.target.value,display_label:e.target.value==='cash_on_delivery'?'Cash on delivery':e.target.value==='eft'?'Bank transfer / EFT':'Debit/Credit card'})}><option value="cash_on_delivery">Cash on delivery</option><option value="card">Debit/Credit card</option><option value="eft">Bank transfer / EFT</option></select></label><label>Display label<input value={form.display_label} onChange={e=>setForm({...form,display_label:e.target.value})} required/></label>{form.method_type==='card'&&<label>Last 4 digits only<input inputMode="numeric" maxLength={4} value={form.last4} onChange={e=>setForm({...form,last4:e.target.value.replace(/\D/g,'').slice(0,4)})} required/></label>}</>}<label className="settings-check"><input type="checkbox" checked={form.is_default} onChange={e=>setForm({...form,is_default:e.target.checked})}/><span>Make this my default</span></label><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':'Save'}</button></div></form></div>}</div></main>;
}