'use client';
import {Suspense,useEffect,useMemo,useState} from 'react';import Link from 'next/link';import {useSearchParams} from 'next/navigation';import {supabase} from '../../lib/supabase';import {Search,ShoppingCart,Store,RefreshCw,MapPin,Navigation,CheckCircle2} from 'lucide-react';

const BRANCHES={
 'pick-n-pay':{name:'Pick n Pay',mark:'PnP',className:'retailer-pnp',address:'Shop No. 1, Hans Coverdale Rd W, Eersterust Plaza, Eersterust, Pretoria, 0022',short:'Eersterust Plaza',directions:'https://www.google.com/maps/search/?api=1&query=Pick+n+Pay+Eersterust+Plaza+Hans+Coverdale+Road'},
 'checkers':{name:'Checkers',mark:'CHECKERS',className:'retailer-checkers',address:'327 Waterloo Lane, Eersterust, Pretoria, Gauteng, South Africa',short:'Eersterust / Waterloo Lane',directions:'https://www.google.com/maps/search/?api=1&query=Checkers+327+Waterloo+Lane+Eersterust+Pretoria'},
 'shoprite':{name:'Shoprite',mark:'SHOPRITE',className:'retailer-shoprite',address:'Corner of Waltloo and Tsamaya Ave, Tshwane Mall, Mamelodi-K18, Pretoria, 0122',short:'Tshwane Mall',directions:'https://www.google.com/maps/search/?api=1&query=Shoprite+Tshwane+Mall+Waltloo+Tsamaya+Pretoria'},
 'woolworths':{name:'Woolworths',mark:'W',className:'retailer-woolworths',address:'128 Letwaba Street, corner Watloo & Stormvoel Road, Mamelodi, Pretoria, 0122',short:'Mamelodi Crossing',directions:'https://www.google.com/maps/search/?api=1&query=Woolworths+Mamelodi+Crossing+128+Letwaba+Street'}
};

const BRAND_DOMAINS={'pick-n-pay':'pnp.co.za','checkers':'checkers.co.za','shoprite':'shoprite.co.za','woolworths':'woolworths.co.za','boxer-denlyn':'boxer.co.za'};
function RetailerLogo({slug,large=false,logoUrl=null}){const b=BRANCHES[slug]||{name:slug,mark:'BG',className:'retailer-generic'};const src=logoUrl||(BRAND_DOMAINS[slug]?('https://www.google.com/s2/favicons?domain='+BRAND_DOMAINS[slug]+'&sz=128'):null);return <div className={'retailer-logo '+b.className+(large?' large':'')} aria-label={b.name+' logo'}>{src?<img src={src} alt="" loading="lazy"/>:<span>{b.mark}</span>}</div>}

function MarketplaceContent(){
 const searchParams=useSearchParams();const requested=searchParams.get('retailer');const [retailers,setRetailers]=useState([]);const [products,setProducts]=useState([]);const [retailer,setRetailer]=useState('all');const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('');const [cartCount,setCartCount]=useState(0);const [animating,setAnimating]=useState(null);
 async function load(){setLoading(true);if(!supabase){setProducts([]);setLoading(false);return}const [{data:rs,error:re},{data:ps,error:pe}]=await Promise.all([supabase.from('retailers').select('id,name,slug,marketplace_category,shopping_location,pickup_address,directions_url,logo_mark,logo_url').eq('active',true).order('name'),supabase.from('retailer_products').select('id,retailer_id,name,description,category,size,price,promo_price,image_url,last_verified_at').eq('available',true).order('name').limit(500)]);if(re||pe){setMsg('The live retailer catalogue is being connected.')}else{setRetailers(rs||[]);setProducts(ps||[]);if(requested){const match=(rs||[]).find(r=>r.slug===requested);if(match)setRetailer(match.id)}}setLoading(false)}
 function syncCart(){try{const cart=JSON.parse(localStorage.getItem('bg_cart')||'[]');setCartCount(cart.reduce((n,x)=>n+Number(x.quantity||0),0))}catch{setCartCount(0)}}\n useEffect(()=>{load();syncCart();const onCart=()=>syncCart();window.addEventListener('bg_cart_updated',onCart);window.addEventListener('storage',onCart);return()=>{window.removeEventListener('bg_cart_updated',onCart);window.removeEventListener('storage',onCart)}},[]);
 const selected=retailers.find(r=>r.id===retailer);const selectedSlug=selected?.slug;const branch=selected?{name:selected.name,mark:selected.logo_mark||selected.name.slice(0,2),className:BRANCHES[selectedSlug]?.className||'retailer-generic',address:selected.pickup_address||'Branch location on file',short:selected.shopping_location||'Participating store',directions:selected.directions_url||BRANCHES[selectedSlug]?.directions}:null;
 const categories=useMemo(()=>{if(!retailer)return [];return [...new Set(products.filter(p=>p.retailer_id===retailer&&p.category).map(p=>p.category))].sort()},[products,retailer]);
 const visible=useMemo(()=>{const term=query.trim().toLowerCase();return products.filter(p=>{const matches=retailer==='all'||p.retailer_id===retailer;const cat=category==='all'||p.category===category;const text=[p.name,p.description,p.category,p.size].filter(Boolean).join(' ').toLowerCase();return matches&&cat&&(!term||text.includes(term))})},[products,retailer,query,category]);
 function chooseStore(id){setRetailer(id);setCategory('all');setQuery('');window.history.replaceState(null,'','/marketplace?retailer='+encodeURIComponent(retailers.find(r=>r.id===id)?.slug||''))}
 function getCart(){try{return JSON.parse(localStorage.getItem('bg_cart')||'[]')}catch{return[]}}
 function setCart(cart){localStorage.setItem('bg_cart',JSON.stringify(cart));window.dispatchEvent(new Event('bg_cart_updated'));syncCart()}
 function changeQty(p,delta){const cart=getCart();const i=cart.findIndex(x=>x.id===p.id);if(i<0)return;cart[i].quantity=Math.max(0,Number(cart[i].quantity||0)+delta);if(cart[i].quantity===0)cart.splice(i,1);setCart(cart)}
 function add(p){const cart=getCart();const price=Number(p.promo_price??p.price);const i=cart.findIndex(x=>x.id===p.id);if(i>=0)cart[i].quantity+=1;else cart.push({id:p.id,name:p.name,price,quantity:1,merchant:p.retailer||'Retailer'});setCart(cart);setAnimating(p.id);setMsg(p.name+' added to cart.');window.setTimeout(()=>setAnimating(null),420)}
 return <main className={'retail-market '+(selectedSlug||'')+' '+(selected?.marketplace_category||'')}>
  <div className="market-shell">
   <div className="market-top"><Link href="/home" className="market-brand"><span className="brand-mark">BG</span><span>Smart Services</span></Link><Link href="/cart" className={"market-cart "+(animating==="cart"?"cart-pulse":"")}><ShoppingCart size={19}/><span>Cart</span>{cartCount>0&&<b className="cart-badge" aria-label={cartCount+" items in cart"}>{cartCount>99?"99+":cartCount}</b>}</Link></div>
   {!selected?<><div className="market-hero"><div><div className="eyebrow">Eersterust Marketplace</div><h1>Choose a store.</h1><p>Select the retailer you want the driver to shop from.</p></div></div><div className="store-selection-grid">{retailers.map(r=>{const b=BRANCHES[r.slug];return <button className={'store-selection-card '+(b?.className||'')} key={r.id} onClick={()=>chooseStore(r.id)}><RetailerLogo slug={r.slug} large logoUrl={r.logo_url}/><div className="store-selection-copy"><h2>{r.name}</h2><p>{b?.short||'Participating store'}</p><span><MapPin size={14}/> {b?.address||'Branch location on file'}</span></div><span className="card-arrow">→</span></button>})}</div></>:<>
    <div className={'retailer-hero '+(branch?.className||'')}><div className="retailer-hero-brand"><RetailerLogo slug={selectedSlug} large logoUrl={selected.logo_url}/><div><div className="eyebrow">BG Smart Services · Store</div><h1>{selected.name}</h1><p>Shop {selected.name} through BG Smart Services.</p></div></div><div className="store-location-card"><div className="location-icon"><MapPin size={18}/></div><div><strong>Driver pickup location</strong><span>{branch?.address||'Branch location on file'}</span></div><a href={branch?.directions} target="_blank" rel="noreferrer"><Navigation size={16}/> Directions</a></div></div>
    <div className="market-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={'Search '+selected.name+' products, brands or categories'}/></div>
    <div className="category-chips"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>All</button>{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>
    {msg&&<div className="notice">{msg}</div>}
    <div className="market-heading"><div><span className="eyebrow">{selected.name} catalogue</span><h2>{loading?'Loading catalogue…':visible.length+' products'}</h2></div><button className="refresh-button" onClick={load} aria-label="Refresh catalogue"><RefreshCw size={17}/></button></div>
    {!loading&&visible.length===0?<div className="market-empty"><Store size={30}/><h2>No products found</h2><p>Try another search or category.</p></div>:<div className="product-grid">{visible.map(p=>{const price=Number(p.promo_price??p.price);const hasPromo=p.promo_price!=null&&Number(p.promo_price)<Number(p.price);return <article className="product-card" key={p.id}><div className="product-image">{p.image_url?<img src={p.image_url} alt=""/>:<RetailerLogo slug={selectedSlug} logoUrl={selected.logo_url}/>}</div><div className="product-store">{selected.name}</div><h3>{p.name}</h3>{p.size&&<p className="product-size">{p.size}</p>}<div className="product-price-row"><div><strong>R{price.toFixed(2)}</strong>{hasPromo&&<del>R{Number(p.price).toFixed(2)}</del>}</div>{(()=>{const cart=getCart();const inCart=cart.find(x=>x.id===p.id);return inCart?<div className="qty-control"><button type="button" aria-label={"Decrease "+p.name} onClick={()=>changeQty(p,-1)}>−</button><span>{inCart.quantity}</span><button type="button" aria-label={"Increase "+p.name} onClick={()=>add({...p,retailer:selected.name})}>+</button></div>:<button className={"btn small add-cart-btn "+(animating===p.id?"added":"")} onClick={e=>{add({...p,retailer:selected.name});const img=e.currentTarget.closest('.product-card')?.querySelector('.product-image img');const cartEl=document.querySelector('.market-cart');if(img&&cartEl&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const ghost=img.cloneNode(true);const a=img.getBoundingClientRect(),b=cartEl.getBoundingClientRect();ghost.className='fly-to-cart';ghost.style.left=a.left+'px';ghost.style.top=a.top+'px';ghost.style.width=Math.min(70,a.width)+'px';ghost.style.height=Math.min(70,a.height)+'px';ghost.style.setProperty('--dx',(b.left+b.width/2-a.left-a.width/2)+'px');ghost.style.setProperty('--dy',(b.top+b.height/2-a.top-a.height/2)+'px');document.body.appendChild(ghost);window.setTimeout(()=>ghost.remove(),430)}}}>{animating===p.id?'Added':'Add'}</button>})()}</div>{p.last_verified_at&&<small className="verified-price">Price verified {new Date(p.last_verified_at).toLocaleDateString('en-ZA')}</small>}</article>})}</div>}
   </>}
   <div className="delivery-note"><CheckCircle2 size={14}/> Driver pickup is tied to the selected store location · Delivery across Eersterust · R65 delivery</div>
  </div>
 </main>}
function MarketplaceFallback(){return <main className="retail-market"><div className="market-shell"><div className="market-empty">Loading marketplace…</div></div></main>}
function Marketplace(){return <Suspense fallback={<MarketplaceFallback/>}><MarketplaceContent/></Suspense>}
export default Marketplace;
