'use client';
import {Suspense,useEffect,useMemo,useState} from 'react';import Link from 'next/link';import {useSearchParams} from 'next/navigation';import {supabase} from '../../lib/supabase';import {Search,ShoppingCart,Store,RefreshCw,MapPin,Navigation,CheckCircle2,X,Plus,Minus,Heart} from 'lucide-react';

const BRAND_DOMAINS={
 'pick-n-pay':'pnp.co.za','checkers':'checkers.co.za','shoprite':'shoprite.co.za','woolworths':'woolworths.co.za',
 'boxer-denlyn':'boxer.co.za','superspar-denlyn':'spar.co.za','kfc-denlyn':'kfc.co.za','kfc-tshwane-regional-mall':'kfc.co.za',
 'chicken-licken-denlyn':'chickenlicken.co.za','chicken-licken-tshwane-regional-mall':'chickenlicken.co.za',
 'nandos-denlyn':'nandos.co.za','mcdonalds-denlyn':'mcdonalds.co.za','steers-tshwane-regional-mall':'steers.co.za',
 'debonairs-pizza-tshwane-regional-mall':'debonairspizza.co.za','hungry-lion-tshwane-regional-mall':'hungrylion.co.za',
 'king-pie-tshwane-regional-mall':'kingpie.co.za','zebros-tshwane-regional-mall':'zebros.co.za'
};
const BRANCH_CLASSES={
 'pick-n-pay':'retailer-pnp','checkers':'retailer-checkers','shoprite':'retailer-shoprite','woolworths':'retailer-woolworths','boxer-denlyn':'retailer-boxer'
};
function retailerClass(slug,category){return BRANCH_CLASSES[slug]||(category==='fast-food'?'retailer-fast-food':'retailer-generic')}

function RetailerLogo({slug,large=false,logoUrl=null,name='Store',category='food-retail'}){const src=logoUrl||(BRAND_DOMAINS[slug]?('https://www.google.com/s2/favicons?domain='+BRAND_DOMAINS[slug]+'&sz=128'):null);return <div className={'retailer-logo '+retailerClass(slug,category)+(large?' large':'')} aria-label={name+' logo'}>{src?<img src={src} alt="" loading="lazy"/>:<span>{name.slice(0,2).toUpperCase()}</span>}</div>}

function MarketplaceContent(){
 const searchParams=useSearchParams();const requested=searchParams.get('retailer');const [retailers,setRetailers]=useState([]);const [products,setProducts]=useState([]);const [retailer,setRetailer]=useState('all');const [query,setQuery]=useState('');const [category,setCategory]=useState('all');const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('');const [cartCount,setCartCount]=useState(0);const [animating,setAnimating]=useState(null);const [selectedProduct,setSelectedProduct]=useState(null);const [quantityPrompt,setQuantityPrompt]=useState(null);const [favoriteIds,setFavoriteIds]=useState(new Set());
 async function load(){setLoading(true);if(!supabase){setProducts([]);setLoading(false);return}const [{data:rs,error:re},{data:ps,error:pe}]=await Promise.all([supabase.from('retailers').select('id,name,slug,marketplace_category,shopping_location,pickup_address,directions_url,logo_mark,logo_url').eq('active',true).order('name'),supabase.from('retailer_products').select('id,retailer_id,name,description,category,size,price,promo_price,image_url,last_verified_at').eq('available',true).order('name').limit(500)]);if(re||pe){setMsg('The live retailer catalogue is being connected.')}else{setRetailers(rs||[]);setProducts(ps||[]);if(requested){const match=(rs||[]).find(r=>r.slug===requested);if(match)setRetailer(match.id)}}setLoading(false)}
 function syncCart(){try{const cart=JSON.parse(localStorage.getItem('bg_cart')||'[]');setCartCount(cart.reduce((n,x)=>n+Number(x.quantity||0),0))}catch{setCartCount(0)}}
 useEffect(()=>{load();syncCart();(async()=>{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(user){const {data}=await supabase.from('customer_favorites').select('product_id').eq('customer_id',user.id);setFavoriteIds(new Set((data||[]).map(x=>x.product_id)))}})();const onCart=()=>syncCart();window.addEventListener('bg_cart_updated',onCart);window.addEventListener('storage',onCart);return()=>{window.removeEventListener('bg_cart_updated',onCart);window.removeEventListener('storage',onCart)}},[]);
 const selected=retailers.find(r=>r.id===retailer);const selectedSlug=selected?.slug;const branch=selected?{name:selected.name,location:selected.shopping_location||'Participating store',category:selected.marketplace_category||'food-retail',address:selected.pickup_address||selected.shopping_location||'Branch location on file',directions:selected.directions_url||null}:null;
 const categories=useMemo(()=>{if(!retailer)return [];return [...new Set(products.filter(p=>p.retailer_id===retailer&&p.category).map(p=>p.category))].sort()},[products,retailer]);
 const visible=useMemo(()=>{const term=query.trim().toLowerCase();return products.filter(p=>{const matches=retailer==='all'||p.retailer_id===retailer;const cat=category==='all'||p.category===category;const text=[p.name,p.description,p.category,p.size].filter(Boolean).join(' ').toLowerCase();return matches&&cat&&(!term||text.includes(term))})},[products,retailer,query,category]);
 function chooseStore(id){setRetailer(id);setCategory('all');setQuery('');window.history.replaceState(null,'','/marketplace?retailer='+encodeURIComponent(retailers.find(r=>r.id===id)?.slug||''))}
 function getCart(){try{return JSON.parse(localStorage.getItem('bg_cart')||'[]')}catch{return[]}}
 function setCart(cart){localStorage.setItem('bg_cart',JSON.stringify(cart));window.dispatchEvent(new Event('bg_cart_updated'));syncCart()}
 function changeQty(p,delta){const cart=getCart();const i=cart.findIndex(x=>x.id===p.id);if(i<0)return;cart[i].quantity=Math.max(0,Number(cart[i].quantity||0)+delta);if(cart[i].quantity===0)cart.splice(i,1);setCart(cart)}
 function add(p){const cart=getCart();const i=cart.findIndex(x=>x.id===p.id);setQuantityPrompt({product:p,quantity:i>=0?Number(cart[i].quantity||0)+1:1,existing:i>=0})}
 async function toggleFavorite(p){if(!supabase){setMsg('Supabase is not configured.');return}const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/signin';return}if(favoriteIds.has(p.id)){const {error}=await supabase.from('customer_favorites').delete().eq('customer_id',user.id).eq('product_id',p.id);if(!error)setFavoriteIds(prev=>{const n=new Set(prev);n.delete(p.id);return n})}else{const {error}=await supabase.from('customer_favorites').insert({customer_id:user.id,product_id:p.id});if(!error)setFavoriteIds(prev=>new Set([...prev,p.id]))}}\n function confirmAdd(){if(!quantityPrompt)return;const p=quantityPrompt.product;const qty=Math.max(1,Number(quantityPrompt.quantity)||1);const cart=getCart();const price=Number(p.promo_price??p.price);const i=cart.findIndex(x=>x.id===p.id);if(i>=0)cart[i].quantity=qty;else cart.push({id:p.id,name:p.name,price,quantity:qty,merchant:p.retailer||selected?.name||'Retailer',retailer_id:p.retailer_id,description:p.description||'',size:p.size||'',image_url:p.image_url||'',last_verified_at:p.last_verified_at||null});setCart(cart);setQuantityPrompt(null);setAnimating(p.id);setMsg(qty+' × '+p.name+' added to cart.');window.setTimeout(()=>setAnimating(null),420)}
 return <main className={'retail-market '+(selectedSlug||'')+' '+(selected?.marketplace_category||'')}>
  <div className="market-shell">
   <div className="market-top"><Link href="/home" className="market-brand"><span className="brand-mark">BG</span><span>Smart Services</span></Link><Link href="/cart" className={"market-cart "+(animating==="cart"?"cart-pulse":"")}><ShoppingCart size={19}/><span>Cart</span>{cartCount>0&&<b className="cart-badge" aria-label={cartCount+" items in cart"}>{cartCount>99?"99+":cartCount}</b>}</Link></div>
   {!selected?<><div className="market-hero"><div><div className="eyebrow">Eersterust Marketplace</div><h1>Choose a store.</h1><p>Select the retailer you want the driver to shop from.</p></div></div><div className="store-selection-grid">{retailers.map(r=><button className={'store-selection-card '+retailerClass(r.slug,r.marketplace_category)} key={r.id} onClick={()=>chooseStore(r.id)}><RetailerLogo slug={r.slug} large logoUrl={r.logo_url} name={r.name} category={r.marketplace_category}/><div className="store-selection-copy"><h2>{r.name}</h2><p>{r.marketplace_category==='fast-food'?'Fast Food':'Food Retail'} · {r.shopping_location||'Participating location'}</p><span><MapPin size={14}/> {r.pickup_address||r.shopping_location||'Branch location on file'}</span></div><span className="card-arrow">→</span></button>)}</div></>:<>
    <div className={'retailer-hero '+retailerClass(selectedSlug,branch?.category)}><div className="retailer-hero-brand"><RetailerLogo slug={selectedSlug} large logoUrl={selected.logo_url} name={selected.name} category={branch?.category}/><div><div className="eyebrow">BG Smart Services · {branch?.category==='fast-food'?'Fast Food':'Food Retail'}</div><h1>{selected.name}</h1><p>{branch?.location} · Real branch catalogue</p></div></div><div className="store-location-card"><div className="location-icon"><MapPin size={18}/></div><div><strong>Driver pickup location</strong><span>{branch?.address||'Branch location on file'}</span></div>{branch?.directions?<a href={branch.directions} target="_blank" rel="noreferrer"><Navigation size={16}/> Directions</a>:null}</div></div>
    <div className="market-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={'Search '+selected.name+' products, brands or categories'}/></div>
    <div className="category-chips"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>All</button>{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>
    {msg&&<div className="notice">{msg}</div>}
    <div className="market-heading"><div><span className="eyebrow">{selected.name} catalogue</span><h2>{loading?'Loading catalogue…':visible.length+' products'}</h2></div><button className="refresh-button" onClick={load} aria-label="Refresh catalogue"><RefreshCw size={17}/></button></div>
    {!loading&&visible.length===0?<div className="market-empty"><Store size={30}/><h2>No products found</h2><p>Try another search or category.</p></div>:<div className="product-grid">{visible.map(p=>{const price=Number(p.promo_price??p.price);const hasPromo=p.promo_price!=null&&Number(p.promo_price)<Number(p.price);return <article className="product-card" key={p.id} role="button" tabIndex={0} onClick={()=>setSelectedProduct(p)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelectedProduct(p)}}}><div className="product-image">{p.image_url?<img src={p.image_url} alt=""/>:<RetailerLogo slug={selectedSlug} logoUrl={selected.logo_url} name={selected.name} category={branch?.category}/>}<button type="button" className={"favorite-toggle "+(favoriteIds.has(p.id)?"is-favorite":"")} onClick={e=>{e.stopPropagation();toggleFavorite(p)}} aria-label={favoriteIds.has(p.id)?"Remove from favorites":"Save to favorites"}><Heart size={18} fill={favoriteIds.has(p.id)?"currentColor":"none"}/></button></div><div className="product-store">{selected.name} · {branch?.location}</div><h3>{p.name}</h3>{p.size&&<p className="product-size">{p.size}</p>}<div className="product-price-row"><div><strong>R{price.toFixed(2)}</strong>{hasPromo&&<del>R{Number(p.price).toFixed(2)}</del>}</div>{(()=>{const cart=getCart();const inCart=cart.find(x=>x.id===p.id);return inCart?<div className="qty-control"><button type="button" aria-label={"Decrease "+p.name} onClick={e=>{e.stopPropagation();changeQty(p,-1)}}>−</button><span>{inCart.quantity}</span><button type="button" aria-label={"Increase "+p.name} onClick={e=>{e.stopPropagation();add({...p,retailer:selected.name})}}>+</button></div>:<button className={"btn small add-cart-btn "+(animating===p.id?"added":"")} onClick={e=>{e.stopPropagation();add({...p,retailer:selected.name});const img=e.currentTarget.closest('.product-card')?.querySelector('.product-image img');const cartEl=document.querySelector('.market-cart');if(img&&cartEl&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const ghost=img.cloneNode(true);const a=img.getBoundingClientRect(),b=cartEl.getBoundingClientRect();ghost.className='fly-to-cart';ghost.style.left=a.left+'px';ghost.style.top=a.top+'px';ghost.style.width=Math.min(70,a.width)+'px';ghost.style.height=Math.min(70,a.height)+'px';ghost.style.setProperty('--dx',(b.left+b.width/2-a.left-a.width/2)+'px');ghost.style.setProperty('--dy',(b.top+b.height/2-a.top-a.height/2)+'px');document.body.appendChild(ghost);window.setTimeout(()=>ghost.remove(),430)}}}>{animating===p.id?'Added':'Add'}</button>})()}</div>{p.last_verified_at&&<small className="verified-price">Price verified {new Date(p.last_verified_at).toLocaleDateString('en-ZA')}</small>}</article>})}</div>}
   </>}
   {selectedProduct&&<div className="product-modal-backdrop" role="presentation" onClick={()=>setSelectedProduct(null)}><section className="product-modal" role="dialog" aria-modal="true" aria-label={selectedProduct.name} onClick={e=>e.stopPropagation()}><button className="product-modal-close" type="button" onClick={()=>setSelectedProduct(null)} aria-label="Close product details"><X size={22}/></button><div className="product-modal-image">{selectedProduct.image_url?<img src={selectedProduct.image_url} alt={selectedProduct.name}/>:<RetailerLogo slug={selectedSlug} logoUrl={selected?.logo_url} name={selected.name} category={branch?.category}/>}</div><div className="product-modal-store">{selected.name} · {branch?.location}</div><h2>{selectedProduct.name}</h2>{selectedProduct.size&&<p className="product-modal-size">{selectedProduct.size}</p>}<p className="product-modal-description">{selectedProduct.description||'Product details are supplied from the selected retailer catalogue.'}</p><div className="product-modal-price"><strong>R{Number(selectedProduct.promo_price??selectedProduct.price).toFixed(2)}</strong>{selectedProduct.promo_price!=null&&Number(selectedProduct.promo_price)<Number(selectedProduct.price)&&<del>R{Number(selectedProduct.price).toFixed(2)}</del>}</div>{selectedProduct.last_verified_at&&<small className="verified-price">Price verified {new Date(selectedProduct.last_verified_at).toLocaleDateString('en-ZA')}</small>}<div className="product-modal-actions">{(()=>{const inCart=getCart().find(x=>x.id===selectedProduct.id);return inCart?<div className="qty-control modal-qty"><button type="button" onClick={()=>changeQty(selectedProduct,-1)} aria-label="Decrease quantity"><Minus size={17}/></button><span>{inCart.quantity}</span><button type="button" onClick={()=>add({...selectedProduct,retailer:selected.name})} aria-label="Increase quantity"><Plus size={17}/></button></div>:<button className="btn btn-primary btn-large" type="button" onClick={()=>add({...selectedProduct,retailer:selected.name})}>Add to Cart</button>})()}<Link className="btn" href="/cart">View Cart</Link></div></section></div>}
   {quantityPrompt&&<div className="product-modal-backdrop" role="presentation" onClick={()=>setQuantityPrompt(null)}><section className="quantity-confirm-modal" role="dialog" aria-modal="true" aria-label="Confirm quantity" onClick={e=>e.stopPropagation()}><button className="product-modal-close" type="button" onClick={()=>setQuantityPrompt(null)} aria-label="Close quantity confirmation"><X size={22}/></button><div className="product-modal-store">{selected?.name} · {branch?.location}</div><h2>Confirm quantity</h2><p>How many <strong>{quantityPrompt.product.name}</strong> do you want to add?</p><div className="confirm-quantity-row"><button type="button" onClick={()=>setQuantityPrompt(q=>({...q,quantity:Math.max(1,Number(q.quantity)-1)}))} aria-label="Decrease quantity"><Minus size={18}/></button><strong>{quantityPrompt.quantity}</strong><button type="button" onClick={()=>setQuantityPrompt(q=>({...q,quantity:Number(q.quantity)+1}))} aria-label="Increase quantity"><Plus size={18}/></button></div><button className="btn btn-primary btn-large" type="button" onClick={confirmAdd}>Confirm {quantityPrompt.quantity} {quantityPrompt.quantity===1?'item':'items'}</button></section></div>}
   <div className="delivery-note"><CheckCircle2 size={14}/> Driver pickup is tied to the selected store location · Delivery across Eersterust · R65 delivery</div>
  </div>
 </main>}
function MarketplaceFallback(){return <main className="retail-market"><div className="market-shell"><div className="market-empty">Loading marketplace…</div></div></main>}
function Marketplace(){return <Suspense fallback={<MarketplaceFallback/>}><MarketplaceContent/></Suspense>}
export default Marketplace;
