'use client';

import {useEffect,useMemo,useState} from 'react';import Link from 'next/link';import {useSearchParams} from 'next/navigation';import {supabase} from '../../lib/supabase';import {Search,ShoppingCart,Store,RefreshCw} from 'lucide-react';

export default function Marketplace(){
 const searchParams=useSearchParams();const requested=searchParams.get('retailer');const [retailers,setRetailers]=useState([]);const [products,setProducts]=useState([]);const [retailer,setRetailer]=useState('all');const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('');
 async function load(){setLoading(true);if(!supabase){setProducts([]);setLoading(false);return}const [{data:rs,error:re},{data:ps,error:pe}]=await Promise.all([supabase.from('retailers').select('id,name,slug').eq('active',true).order('name'),supabase.from('retailer_products').select('id,retailer_id,name,description,category,size,price,promo_price,image_url,last_verified_at').eq('available',true).order('name').limit(500)]);if(re||pe){setMsg('The live retailer catalogue is being connected.')}else{setRetailers(rs||[]);setProducts(ps||[]);if(requested){const match=(rs||[]).find(r=>r.slug===requested);if(match)setRetailer(match.id)}}setLoading(false)}
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{const term=query.trim().toLowerCase();return products.filter(p=>{const matches=retailer==='all'||p.retailer_id===retailer;const text=[p.name,p.description,p.category,p.size].filter(Boolean).join(' ').toLowerCase();return matches&&(!term||text.includes(term))})},[products,retailer,query]);
 function add(p){const cart=JSON.parse(localStorage.getItem('bg_cart')||'[]');const price=Number(p.promo_price??p.price);const i=cart.findIndex(x=>x.id===p.id);if(i>=0)cart[i].quantity+=1;else cart.push({id:p.id,name:p.name,price,quantity:1,merchant:p.retailer||'Retailer'});localStorage.setItem('bg_cart',JSON.stringify(cart));setMsg(p.name+' added to cart.')}
 const selected=retailers.find(r=>r.id===retailer);
 return <main className="retail-market"><div className="market-shell"><div className="market-top"><Link href="/home" className="market-brand"><span className="brand-mark">BG</span><span>Smart Services</span></Link><Link href="/cart" className="market-cart"><ShoppingCart size={19}/><span>Cart</span></Link></div>
 <div className="market-hero"><div><div className="eyebrow">Eersterust Marketplace</div><h1>{selected?selected.name:'Choose a store.'}</h1><p>{selected?'Shop this store through BG Smart Services. Prices and availability are shown from the live catalogue.':'Choose a participating store, then shop its products.'}</p></div></div>
 <div className="market-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products, brands or categories"/></div>
 <div className="retailer-tabs"><button className={retailer==='all'?'active':''} onClick={()=>setRetailer('all')}><Store size={17}/>All stores</button>{retailers.map(r=><button key={r.id} className={retailer===r.id?'active':''} onClick={()=>setRetailer(r.id)}>{r.name}</button>)}</div>
 {msg&&<div className="notice">{msg}</div>}
 <div className="market-heading"><div><span className="eyebrow">{selected?selected.name:'All participating stores'}</span><h2>{loading?'Loading catalogue…':visible.length+' products'}</h2></div><button className="refresh-button" onClick={load} aria-label="Refresh catalogue"><RefreshCw size={17}/></button></div>
 {!loading&&visible.length===0?<div className="market-empty"><Store size={30}/><h2>No products found</h2><p>Try another search or store.</p></div>:<div className="product-grid">{visible.map(p=>{const price=Number(p.promo_price??p.price);const hasPromo=p.promo_price!=null&&Number(p.promo_price)<Number(p.price);const store=retailers.find(r=>r.id===p.retailer_id)?.name||'Retailer';return <article className="product-card" key={p.id}><div className="product-image">{p.image_url?<img src={p.image_url} alt=""/>:<Store size={30}/>}</div><div className="product-store">{store}</div><h3>{p.name}</h3>{p.size&&<p className="product-size">{p.size}</p>}<div className="product-price-row"><div><strong>R{price.toFixed(2)}</strong>{hasPromo&&<del>R{Number(p.price).toFixed(2)}</del>}</div><button className="btn small" onClick={()=>add({...p,retailer:store})}>Add</button></div>{p.last_verified_at&&<small className="verified-price">Price verified {new Date(p.last_verified_at).toLocaleDateString('en-ZA')}</small>}</article>})}</div>}
 <div className="delivery-note">Delivery across Eersterust · R65 delivery · Retailer pricing and availability can change by store.</div></div></main>}
